// DuneCity direct transport. Bundled from the installed p2pkit dependency pinned in platform/web/package.json (github:QuixThe2nd/p2pkit#257f3c8eb0c0cf373298225e54c8d09d2f896a42, MIT) via its documented package exports. Generated by tools/p2pkit-build/build.mjs.
(() => {
  var __defProp = Object.defineProperty;
  var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
  var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

  // platform/web/node_modules/p2pkit/dist/chunk-HQHLJTRF.js
  var DEFAULT_MAX_PACKET_SIZE = 16e3;
  var CHUNK_LIMITS = Object.freeze({
    /** Maximum characters of payload per fragment (also the default `maxPacketSize`). */
    packetChars: 16e3,
    /** Maximum UTF-8 bytes of one whole message, counting characters and bytes. */
    messageBytes: 1048576,
    /** Maximum fragments (`n`) of one message. */
    fragments: 128,
    /** Maximum concurrently-incomplete messages kept in the inbox. */
    pendingGroups: 16,
    /** Maximum total UTF-8 bytes held across all incomplete messages. */
    pendingBytes: 4194304,
    /** A partially-received message older than this fails (see {@link Chunker.checkDeadline}). */
    lifetimeMs: 15e3
  });
  function validId(id) {
    return typeof id === "string" && /^[A-Za-z0-9_-]{1,64}$/.test(id);
  }
  var encoder = new TextEncoder();
  var Chunker = class {
    constructor(options = {}) {
      __publicField(this, "maxPacketSize");
      __publicField(this, "hardened");
      __publicField(this, "inbox", /* @__PURE__ */ new Map());
      __publicField(this, "bytes", 0);
      this.hardened = options.hardened === true;
      this.maxPacketSize = options.maxPacketSize ?? DEFAULT_MAX_PACKET_SIZE;
      if (this.hardened && (!Number.isSafeInteger(this.maxPacketSize) || this.maxPacketSize < 1 || this.maxPacketSize > CHUNK_LIMITS.packetChars)) {
        throw new Error("Invalid chunk size");
      }
    }
    /**
     * Split `data` into JSON-encoded {@link ChunkPacket}s under `id`. Always yields
     * at least one packet (even for the empty string). Send each yielded string as
     * one transport message.
     */
    *split(id, data) {
      if (this.hardened) {
        if (!validId(id) || typeof data !== "string" || data.length > CHUNK_LIMITS.messageBytes || encoder.encode(data).length > CHUNK_LIMITS.messageBytes) {
          throw new Error("Message too large");
        }
        const total = Math.max(1, Math.ceil(data.length / this.maxPacketSize));
        if (total > CHUNK_LIMITS.fragments) throw new Error("Too many fragments");
        yield* this.splitUnchecked(id, data, total);
        return;
      }
      yield* this.splitUnchecked(id, data, data.length === 0 ? 1 : Math.ceil(data.length / this.maxPacketSize));
    }
    *splitUnchecked(id, data, n) {
      const size = this.maxPacketSize;
      for (let i = 0; i < n; i++) {
        const packet = { id, i, n, part: data.slice(i * size, (i + 1) * size) };
        yield JSON.stringify(packet);
      }
    }
    /**
     * Fail if any partially-received message has been incomplete for longer than
     * `CHUNK_LIMITS.lifetimeMs`. Called by hardened `ingest` on every fragment and
     * by direct-mode transports on a timer, so a peer that goes silent mid-message
     * cannot pin memory forever. No-op when nothing is pending.
     */
    checkDeadline(now = performance.now()) {
      for (const entry of this.inbox.values()) {
        if (now - entry.created >= CHUNK_LIMITS.lifetimeMs) throw new Error("Incomplete message expired");
      }
    }
    /**
     * Feed one received {@link ChunkPacket}. Returns the fully reassembled string
     * once the final missing fragment arrives, otherwise `undefined`. Duplicate
     * fragments are ignored; fragments may arrive in any order.
     *
     * Hardened mode additionally validates the fragment's shape (throwing on
     * malformed, conflicting or budget-exceeding input — never returning a
     * corrupted payload) and enforces {@link CHUNK_LIMITS}.
     */
    ingest(packet) {
      if (this.hardened) return this.ingestHardened(packet);
      const { id, i, n, part } = packet;
      if (n <= 1) return part;
      let entry = this.inbox.get(id);
      if (!entry) {
        entry = { parts: new Array(n).fill(void 0), received: 0, bytes: 0, created: 0 };
        this.inbox.set(id, entry);
      }
      if (i < 0 || i >= n) return void 0;
      if (entry.parts[i] === void 0) {
        entry.parts[i] = part;
        entry.received++;
      }
      if (entry.received === n) {
        this.inbox.delete(id);
        return entry.parts.join("");
      }
      return void 0;
    }
    ingestHardened(packet) {
      this.checkDeadline();
      if (!packet || typeof packet !== "object" || Array.isArray(packet)) throw new Error("Invalid fragment");
      const { id, i, n, part } = packet;
      if (!validId(id) || !Number.isSafeInteger(n) || n < 1 || n > CHUNK_LIMITS.fragments || !Number.isSafeInteger(i) || i < 0 || i >= n || typeof part !== "string" || part.length > this.maxPacketSize) {
        throw new Error("Invalid fragment");
      }
      let entry = this.inbox.get(id);
      if (entry && entry.parts.length !== n) throw new Error("Fragment count changed");
      const bytes = encoder.encode(part).length;
      if (n === 1) return part;
      if (!entry) {
        if (this.inbox.size >= CHUNK_LIMITS.pendingGroups) throw new Error("Too many incomplete messages");
        entry = { parts: new Array(n).fill(void 0), received: 0, bytes: 0, created: performance.now() };
        this.inbox.set(id, entry);
      }
      const previous = entry.parts[i];
      if (previous !== void 0) {
        if (previous !== part) throw new Error("Conflicting fragment");
        return void 0;
      }
      if (bytes > CHUNK_LIMITS.messageBytes - entry.bytes || bytes > CHUNK_LIMITS.pendingBytes - this.bytes) {
        throw new Error("Reassembly budget exceeded");
      }
      entry.parts[i] = part;
      entry.received++;
      entry.bytes += bytes;
      this.bytes += bytes;
      if (entry.received !== n) return void 0;
      this.inbox.delete(id);
      this.bytes -= entry.bytes;
      return entry.parts.join("");
    }
    /** Drop any partially-received payloads (e.g. on disconnect). */
    reset() {
      this.inbox.clear();
      this.bytes = 0;
    }
  };

  // platform/web/node_modules/p2pkit/dist/chunk-TZGXUDQM.js
  var Emitter = class {
    constructor() {
      __publicField(this, "handlers", {});
    }
    /** Subscribe to `event`. Returns an unsubscribe function. */
    on(event, handler) {
      var _a;
      ((_a = this.handlers)[event] ?? (_a[event] = /* @__PURE__ */ new Set())).add(handler);
      return () => this.off(event, handler);
    }
    /** Subscribe once; the handler is removed after its first invocation. */
    once(event, handler) {
      const wrap = ((...args) => {
        this.off(event, wrap);
        handler(...args);
      });
      return this.on(event, wrap);
    }
    /** Remove a previously registered handler. */
    off(event, handler) {
      this.handlers[event]?.delete(handler);
    }
    /** Synchronously invoke every handler registered for `event`. */
    emit(event, ...args) {
      const set = this.handlers[event];
      if (!set) return;
      for (const handler of [...set]) handler(...args);
    }
    /** Remove all handlers for one event, or all events when `event` is omitted. */
    removeAll(event) {
      if (event !== void 0) this.handlers[event]?.clear();
      else for (const key of Object.keys(this.handlers)) delete this.handlers[key];
    }
    /** Number of handlers registered for `event`. */
    listenerCount(event) {
      return this.handlers[event]?.size ?? 0;
    }
  };
  function randomId(bytes = 16) {
    const buf = new Uint8Array(bytes);
    globalThis.crypto.getRandomValues(buf);
    let out = "";
    for (const b of buf) out += b.toString(16).padStart(2, "0");
    return out;
  }
  var DEFAULT_ICE_SERVERS = [
    { urls: "stun:stun.l.google.com:19302" },
    { urls: "stun:stun1.l.google.com:19302" },
    { urls: "stun:stun2.l.google.com:19302" },
    { urls: "stun:global.stun.twilio.com:3478" }
  ];

  // platform/web/node_modules/p2pkit/dist/chunk-FUPXCS3V.js
  var RTC_SEND_QUEUE_FLUSH_THRESHOLD = 1 << 20;
  function utf8ByteLength(text) {
    let bytes = 0;
    for (let i = 0; i < text.length; i++) {
      const code = text.charCodeAt(i);
      if (code < 128) {
        bytes += 1;
      } else if (code < 2048) {
        bytes += 2;
      } else if (code >= 55296 && code <= 56319) {
        const low = i + 1 < text.length ? text.charCodeAt(i + 1) : 0;
        if (low >= 56320 && low <= 57343) {
          bytes += 4;
          i++;
        } else {
          bytes += 3;
        }
      } else {
        bytes += 3;
      }
    }
    return bytes;
  }
  function payloadByteLength(data) {
    if (typeof data === "string") return utf8ByteLength(data);
    return data.byteLength;
  }
  function snapshotPayload(data) {
    if (typeof data === "string") return data;
    const view = data instanceof ArrayBuffer ? new Uint8Array(data) : new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
    const copy = new Uint8Array(view.byteLength);
    copy.set(view);
    return copy;
  }
  var RTCDataChannelSendQueue = class {
    constructor(options = {}) {
      __publicField(this, "channel");
      __publicField(this, "highWaterBytes");
      __publicField(this, "lowWaterBytes");
      __publicField(this, "onDrain");
      __publicField(this, "onSendError");
      __publicField(this, "maxQueuedBytes");
      __publicField(this, "maxQueuedJobs");
      /** The single authoritative FIFO of retained-but-undelivered work. */
      __publicField(this, "entries", []);
      /** Wire bytes of job payloads still retained (payload entries count via {@link RTCDataChannelSendQueue.bufferedAmount}). */
      __publicField(this, "queuedBytes", 0);
      __publicField(this, "drainTimer");
      __publicField(this, "lowHandler");
      __publicField(this, "flushing", false);
      __publicField(this, "backpressured", false);
      /** Set once a native send throws mid-drain; further sends reject until re-attach. */
      __publicField(this, "failureError");
      this.highWaterBytes = options.highWaterBytes;
      if (options.highWaterBytes !== void 0) {
        this.lowWaterBytes = options.lowWaterBytes ?? Math.floor(options.highWaterBytes / 2);
      } else {
        this.lowWaterBytes = options.lowWaterBytes;
      }
      this.onDrain = options.onDrain;
      this.onSendError = options.onSendError;
      this.maxQueuedBytes = options.maxQueuedBytes;
      this.maxQueuedJobs = options.maxQueuedJobs;
    }
    /** Bind (or re-bind) this queue to a live data channel. */
    attach(channel) {
      this.detach();
      this.channel = channel;
      if (this.highWaterBytes === void 0) return;
      channel.bufferedAmountLowThreshold = this.lowWaterBytes;
      this.lowHandler = () => this.drain();
      if (channel.addEventListener) channel.addEventListener("bufferedamountlow", this.lowHandler);
      else channel.onbufferedamountlow = this.lowHandler;
    }
    /** Detach from the current channel and clear any pending sends. */
    detach() {
      const channel = this.channel;
      if (channel && this.lowHandler) {
        if (channel.removeEventListener) channel.removeEventListener("bufferedamountlow", this.lowHandler);
        else channel.onbufferedamountlow = null;
      }
      this.failEntries(new Error("RTC send queue detached before delivery"));
      this.channel = void 0;
      this.lowHandler = void 0;
      this.failureError = void 0;
      this.flushing = false;
      this.backpressured = false;
    }
    /** Channel `bufferedAmount` plus wire bytes still waiting in this queue. */
    get bufferedAmount() {
      let pending = 0;
      for (const entry of this.entries) {
        if (entry.kind === "payload") {
          pending += payloadByteLength(entry.data);
        } else {
          for (let i = entry.next; i < entry.payloads.length; i++) {
            pending += payloadByteLength(entry.payloads[i]);
          }
        }
      }
      return (this.channel?.bufferedAmount ?? 0) + pending;
    }
    /**
     * Synchronous, lossy send attempt: returns `false` (dropping the payload)
     * when the channel is at or above the high-water mark, instead of queueing.
     *
     * Why this exists beside the async {@link send}: Emscripten `ccall` exports
     * (and other synchronous producers of lossy, time-sensitive traffic such as
     * per-tick game state) must learn acceptance in the same tick — a promise
     * would answer after the moment to resend has passed. Without
     * {@link highWaterBytes} there is no drop policy: the payload is always
     * accepted (`true`) — sent directly when the FIFO is empty, or ordered
     * behind retained work otherwise.
     *
     * Never overtakes older work, and never queues a refusal: the high-water
     * check comes first — a payload offered while the channel is at/above the
     * mark is refused with nothing retained (the original queue contract) — and
     * below the mark, when payloads or jobs are still queued, this appends
     * behind them (snapshot included) and reports `true`: the payload was
     * accepted and will flush in order. That single FIFO holds whether or not a
     * watermark is configured; without one there is no drop policy, so pending
     * work forces ordering but never refusal.
     */
    trySend(data) {
      const channel = this.channel;
      if (!channel || channel.readyState !== "open") return false;
      if (this.failureError !== void 0) return false;
      if (this.highWaterBytes !== void 0 && channel.bufferedAmount >= this.highWaterBytes) {
        return false;
      }
      if (this.entries.length > 0) {
        this.entries.push({ kind: "payload", data: snapshotPayload(data) });
        this.drain();
        return true;
      }
      channel.send(data);
      if (this.highWaterBytes === void 0) return true;
      if (channel.bufferedAmount >= this.highWaterBytes) this.backpressured = true;
      return true;
    }
    /**
     * Send one payload. One FIFO governs this and every other public send entry:
     * while any older work — payload or job — is still queued, the new payload
     * appends behind it rather than sending directly, whether or not a watermark
     * is configured. With {@link highWaterBytes} configured, payloads are also
     * queued (never dropped) while the channel is at or above the high-water
     * mark; with no watermark, the legacy direct send plus 1 MB polling flush
     * applies (same as stock RTCTransport). The promise resolves on acceptance
     * into the queue (the historical contract), not on delivery; a later flush
     * failure surfaces through {@link RTCDataChannelSendQueueOptions.onSendError}.
     */
    async send(data) {
      const channel = this.channel;
      if (!channel || channel.readyState !== "open") throw new Error("RTC data channel is not open");
      if (this.failureError !== void 0) throw this.failureError;
      if (this.entries.length > 0) {
        if (this.highWaterBytes !== void 0 && channel.bufferedAmount >= this.highWaterBytes) {
          this.backpressured = true;
        }
        this.entries.push({ kind: "payload", data: snapshotPayload(data) });
        this.drain();
        return;
      }
      if (this.highWaterBytes === void 0) {
        channel.send(data);
        await this.pollFlush(channel);
        return;
      }
      if (channel.bufferedAmount >= this.highWaterBytes) {
        this.backpressured = true;
        this.entries.push({ kind: "payload", data: snapshotPayload(data) });
        this.drain();
        return;
      }
      channel.send(data);
      if (channel.bufferedAmount >= this.highWaterBytes) this.backpressured = true;
    }
    /**
     * Opt-in job API for bounded, lossless consumers (direct-mode
     * {@link RTCTransport} in `src/transports/rtc.ts`): submit a burst of payloads
     * as ONE first-in-first-out unit — every payload of a job is handed to
     * `channel.send()` in order, and no later entry's payload is sent before an
     * earlier one has fully drained, so whole messages keep their order on the
     * wire. The promise resolves only after the last payload was actually handed
     * to the channel (not merely accepted while backpressured), and rejects —
     * without sending anything further — when the job would exceed
     * {@link maxQueuedBytes}/{@link maxQueuedJobs} retention, when the channel is
     * or becomes unusable, or when the queue detaches first ({@link detach}).
     *
     * While the channel sits above the high-water mark, delivery retries on a
     * short poll timer (bounded: the timer only lives while work is retained),
     * so progress does not depend solely on `bufferedamountlow` firing.
     */
    sendJob(payloads) {
      return new Promise((resolve, reject) => {
        this.enqueueJob(payloads, resolve, reject);
      });
    }
    /**
     * Synchronous counterpart to {@link sendJob} (same bounded acceptance, same
     * FIFO): returns whether the job was accepted by this bounded queue — never a
     * promise masquerading as success. Settlement is silent: delivery completes
     * unnoticed and rejection surfaces nowhere, matching producers that cannot
     * await (e.g. Emscripten `ccall` bridges) — a native send failure during the
     * drain is reported once through {@link RTCDataChannelSendQueueOptions.onSendError}
     * instead of throwing here.
     */
    tryJob(payloads) {
      return this.enqueueJob(
        payloads,
        () => {
        },
        () => {
        }
      );
    }
    enqueueJob(payloads, resolve, reject) {
      const channel = this.channel;
      if (!channel || channel.readyState !== "open") {
        reject(new Error("RTC data channel is not open"));
        return false;
      }
      if (this.failureError !== void 0) {
        reject(this.failureError);
        return false;
      }
      if (payloads.length === 0) {
        resolve();
        return true;
      }
      const bytes = payloads.reduce((total, item) => total + payloadByteLength(item), 0);
      if (this.overRetentionLimit(bytes)) {
        reject(new Error("RTC send queue retention limit exceeded"));
        return false;
      }
      this.entries.push({
        kind: "job",
        payloads: payloads.map(snapshotPayload),
        bytes,
        next: 0,
        resolve,
        reject
      });
      this.queuedBytes += bytes;
      this.drain();
      return true;
    }
    overRetentionLimit(bytes) {
      if (this.maxQueuedBytes !== void 0 && this.queuedBytes + bytes > this.maxQueuedBytes) {
        return true;
      }
      if (this.maxQueuedJobs !== void 0) {
        let jobs = 0;
        for (const entry of this.entries) {
          if (entry.kind === "job") jobs++;
        }
        if (jobs >= this.maxQueuedJobs) return true;
      }
      return false;
    }
    /**
     * The single owner of retained-work delivery: walks the FIFO head-first,
     * handing payloads to the channel while it stays under the applicable water
     * mark. Payload entries keep the raw flush contract (send only strictly below
     * the high-water mark); job entries keep the job contract (send down to the
     * mark, including the legacy 1 MB threshold when no high-water mark is
     * configured). While blocked, a short poll timer keeps progress independent
     * of `bufferedamountlow` events. Any native `channel.send()` throw is
     * contained here — see {@link handleSendFailure}.
     */
    drain() {
      if (this.flushing) return;
      this.flushing = true;
      try {
        this.cancelDrainTimer();
        while (this.entries.length > 0) {
          const channel = this.channel;
          if (!channel || channel.readyState !== "open") {
            this.failEntries(new Error("RTC data channel is not open"));
            return;
          }
          const entry = this.entries[0];
          if (entry.kind === "payload") {
            const high = this.highWaterBytes;
            if (high !== void 0 && channel.bufferedAmount >= high) {
              this.backpressured = true;
              this.scheduleDrainTimer();
              return;
            }
            channel.send(entry.data);
            this.entries.shift();
          } else {
            const limit = this.highWaterBytes ?? RTC_SEND_QUEUE_FLUSH_THRESHOLD;
            if (channel.bufferedAmount > limit) {
              this.scheduleDrainTimer();
              return;
            }
            const payload = entry.payloads[entry.next];
            channel.send(payload);
            entry.next++;
            this.queuedBytes -= payloadByteLength(payload);
            if (entry.next >= entry.payloads.length) {
              this.entries.shift();
              entry.resolve();
            }
          }
        }
      } catch (error) {
        this.handleSendFailure(error);
        return;
      } finally {
        this.flushing = false;
      }
      if (this.backpressured) {
        this.backpressured = false;
        this.onDrain?.();
      }
    }
    /**
     * Contain a native `channel.send()` throw from the drain — whether it happened
     * inside a timer callback, a low-water flush, or synchronously under
     * {@link tryJob}/{@link trySend}: reject every pending job (a partially-sent
     * job rejects — accepted is not delivered), release all retained payloads,
     * zero the byte budget, stop the poll timer, and surface the failure exactly
     * once through {@link RTCDataChannelSendQueueOptions.onSendError} so the
     * owning transport's error/disconnect path runs even for synchronous
     * producers. The queue refuses further work until re-attached.
     */
    handleSendFailure(cause) {
      this.cancelDrainTimer();
      const error = cause instanceof Error ? cause : new Error(String(cause));
      this.failureError = error;
      this.queuedBytes = 0;
      this.backpressured = false;
      for (const entry of this.entries.splice(0)) {
        if (entry.kind === "job") entry.reject(error);
      }
      this.onSendError?.(error);
    }
    /** Reject all retained jobs (channel gone or queue detached) and drop payloads. */
    failEntries(error) {
      this.cancelDrainTimer();
      this.queuedBytes = 0;
      for (const entry of this.entries.splice(0)) {
        if (entry.kind === "job") entry.reject(error);
      }
    }
    async pollFlush(channel) {
      while (channel.readyState === "open" && channel.bufferedAmount > RTC_SEND_QUEUE_FLUSH_THRESHOLD) {
        await new Promise((resolve) => setTimeout(resolve, 10));
      }
    }
    scheduleDrainTimer() {
      if (this.drainTimer !== void 0) return;
      this.drainTimer = setTimeout(() => {
        this.drainTimer = void 0;
        this.drain();
      }, 10);
      if (typeof this.drainTimer === "object" && this.drainTimer && typeof this.drainTimer.unref === "function") {
        this.drainTimer.unref();
      }
    }
    cancelDrainTimer() {
      if (this.drainTimer !== void 0) {
        clearTimeout(this.drainTimer);
        this.drainTimer = void 0;
      }
    }
  };
  var DIRECT_MAX_BUFFERED = 1 << 20;
  var DIRECT_MAX_OUTGOING_BYTES = 4 << 20;
  var DIRECT_MAX_OUTGOING_MESSAGES = 128;
  var DIRECT_MAX_SIGNALS = 128;
  var DIRECT_MAX_SDP = 65536;
  var DIRECT_MAX_CANDIDATE = 2048;
  var DIRECT_MAX_FRAME_BYTES = 131072;
  var DIRECT_MAX_PACKETS_PER_SECOND = 4096;
  var DIRECT_MAX_BYTES_PER_SECOND = 16 * 1024 * 1024;
  function directIceServers(servers) {
    if (!Array.isArray(servers) || servers.length > 8) throw new Error("Invalid STUN configuration");
    return servers.map((server) => {
      const urls = typeof server.urls === "string" ? [server.urls] : server.urls;
      if (!Array.isArray(urls) || urls.length === 0 || urls.length > 8 || server.username || server.credential || urls.some(
        (url) => typeof url !== "string" || url.length > 256 || !/^stuns?:[a-zA-Z0-9.\[\]:-]+$/.test(url)
      )) {
        throw new Error("Only STUN is supported for direct play");
      }
      return { urls: [...urls] };
    });
  }
  function validateDirectCandidate(candidate) {
    if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) {
      throw new Error("Invalid ICE candidate");
    }
    const { candidate: value, sdpMid, sdpMLineIndex } = candidate;
    if (typeof value !== "string" || value.length > DIRECT_MAX_CANDIDATE || /[\r\n\0]/.test(value) || value !== "" && (!value.startsWith("candidate:") || /\styp\s+relay(?:\s|$)/.test(value) || !/\styp (host|srflx|prflx)(?:\s|$)/.test(value)) || sdpMid !== void 0 && sdpMid !== null && (typeof sdpMid !== "string" || !/^[A-Za-z0-9_-]{1,64}$/.test(sdpMid)) || sdpMLineIndex !== void 0 && sdpMLineIndex !== null && (!Number.isInteger(sdpMLineIndex) || sdpMLineIndex < 0 || sdpMLineIndex > 16)) {
      throw new Error("Invalid direct ICE candidate");
    }
  }
  function validateDirectDescription(description) {
    if (!description || typeof description !== "object") throw new Error("Invalid session description");
    const { type, sdp } = description;
    if (type !== "offer" && type !== "answer" || typeof sdp !== "string" || sdp.length > DIRECT_MAX_SDP || sdp.includes("\0") || !/^v=0\r?\n/.test(sdp) || !/^a=fingerprint:sha-256 (?:[0-9A-Fa-f]{2}:){31}[0-9A-Fa-f]{2}\r?$/m.test(sdp) || (sdp.match(/^a=fingerprint:/gm)?.length ?? 0) !== 1 || (sdp.match(/^m=application /gm)?.length ?? 0) !== 1 || /^m=(?!application )/m.test(sdp)) {
      throw new Error("Invalid data-channel description");
    }
    let count = 0;
    for (const line of sdp.split(/\r?\n/)) {
      if (line.startsWith("a=candidate:")) {
        if (++count > DIRECT_MAX_SIGNALS) throw new Error("Too many ICE candidates");
        validateDirectCandidate({ candidate: line.slice(2) });
      }
    }
  }
  function toUint8Array(value) {
    if (value instanceof Uint8Array) return value;
    if (value instanceof ArrayBuffer) return new Uint8Array(value);
    if (ArrayBuffer.isView(value)) return new Uint8Array(value.buffer, value.byteOffset, value.byteLength);
    throw new Error("raw RTC payloads must be an ArrayBuffer or ArrayBufferView");
  }
  var textEncoder = new TextEncoder();
  function isFullyReliable(value) {
    return value === null || value === 65535;
  }
  var RTCTransportConnectTimeoutError = class extends Error {
    constructor(timeoutMs) {
      super(`RTC transport connect timed out after ${timeoutMs}ms`);
      __publicField(this, "name", "ErrorTimeout");
      __publicField(this, "code", "ERR_RTC_CONNECT_TIMEOUT");
    }
  };
  var RTCTransportBackpressureDropError = class extends Error {
    constructor(channelIndex) {
      super(`RTC channel ${channelIndex} dropped raw payload under backpressure (drop mode)`);
      __publicField(this, "name", "ErrorBackpressureDrop");
      __publicField(this, "code", "ERR_RTC_BACKPRESSURE_DROP");
    }
  };
  var RTCTransport = class {
    constructor(options) {
      __publicField(this, "remote");
      __publicField(this, "name", "rtc");
      __publicField(this, "self");
      __publicField(this, "signalling");
      __publicField(this, "emitter", new Emitter());
      __publicField(this, "channelStates", []);
      __publicField(this, "channelSpecs");
      __publicField(this, "expectedChannelCount");
      __publicField(this, "connectTimeoutMs");
      __publicField(this, "connectTimer");
      __publicField(this, "connectEmitted", false);
      __publicField(this, "openChannels", /* @__PURE__ */ new Set());
      __publicField(this, "pc");
      __publicField(this, "remoteDescriptionSet", false);
      __publicField(this, "pendingCandidates", []);
      __publicField(this, "closed", false);
      __publicField(this, "emittedClose", false);
      __publicField(this, "raw");
      __publicField(this, "direct");
      __publicField(this, "initiator");
      __publicField(this, "signalCount", 0);
      __publicField(this, "candidateCount", 0);
      __publicField(this, "signalChain", Promise.resolve());
      __publicField(this, "unsubscribeSignalling");
      __publicField(this, "expiryTimer");
      __publicField(this, "rttMs", 0);
      __publicField(this, "rttTimer");
      __publicField(this, "onSignal", (message) => {
        if (this.direct) {
          if (this.closed || this.emittedClose) return;
          if (!message || typeof message !== "object" || !("to" in message) || message.from !== this.remote || message.to !== this.self) {
            return;
          }
          if (++this.signalCount > DIRECT_MAX_SIGNALS) {
            this.signalCount--;
            this.failClosed("Too many connection messages");
            return;
          }
          this.signalChain = this.signalChain.then(() => this.handleSignal(message)).catch(() => {
            if (!this.closed && !this.emittedClose) this.failClosed("Invalid direct connection details");
          }).finally(() => {
            this.signalCount--;
          });
          return;
        }
        void this.handleSignal(message);
      });
      this.self = options.self;
      this.remote = options.remote;
      this.signalling = options.signalling;
      this.channelSpecs = options.channels;
      this.expectedChannelCount = options.channels?.length ?? 1;
      this.connectTimeoutMs = options.connectTimeoutMs;
      this.raw = options.raw === true;
      this.direct = options.direct === true;
      this.initiator = options.initiator;
      if (this.direct && options.channels) {
        throw new Error("direct mode uses a single ordered/reliable channel; channels is not supported");
      }
      if (this.direct && this.raw) {
        throw new Error("direct mode sends JSON values; raw is not supported");
      }
      const iceServers = this.direct ? directIceServers(options.iceServers ?? DEFAULT_ICE_SERVERS) : options.iceServers ?? DEFAULT_ICE_SERVERS;
      this.pc = new options.backend.RTCPeerConnection({ iceServers });
      if (this.connectTimeoutMs !== void 0) {
        this.connectTimer = setTimeout(() => this.handleConnectTimeout(), this.connectTimeoutMs);
      }
      this.pc.onicecandidate = (ev) => {
        if (ev.candidate) {
          if (this.direct) {
            try {
              const candidate = ev.candidate.toJSON();
              validateDirectCandidate(candidate);
              if (candidate.candidate === "") return;
              this.signalling.send({
                iceCandidate: candidate,
                from: this.self,
                to: this.remote
              });
            } catch {
              this.failClosed("Could not exchange direct connection details");
            }
            return;
          }
          this.signalling.send({
            iceCandidate: ev.candidate.toJSON(),
            from: this.self,
            to: this.remote
          });
        }
      };
      this.pc.onconnectionstatechange = () => {
        const state = this.pc.connectionState;
        if (state === "failed" || state === "closed" || state === "disconnected") this.handleClose();
      };
      if (options.initiator) {
        if (options.channels) {
          for (let i = 0; i < options.channels.length; i++) {
            const spec = options.channels[i];
            this.setupChannel(
              i,
              this.pc.createDataChannel(spec.label, {
                ordered: spec.ordered,
                maxRetransmits: spec.maxRetransmits
              }),
              options
            );
          }
        } else {
          this.setupChannel(
            0,
            this.pc.createDataChannel(
              options.label ?? "p2pkit",
              this.direct ? { ordered: true } : void 0
            ),
            options
          );
        }
        void (this.direct ? this.negotiate().catch(() => this.failClosed("Direct connection negotiation failed")) : this.negotiate());
      } else {
        this.pc.ondatachannel = (ev) => {
          const label = ev.channel.label;
          if (options.channels) {
            const index = options.channels.findIndex((spec) => spec.label === label);
            if (index === -1) return;
            this.setupChannel(index, ev.channel, options);
          } else {
            this.setupChannel(0, ev.channel, options);
          }
        };
      }
      if (this.direct) {
        this.expiryTimer = setInterval(() => {
          if (this.closed || this.emittedClose) {
            this.stopExpiryTimer();
            return;
          }
          try {
            for (const state of this.channelStates) state.chunker.checkDeadline();
          } catch {
            this.failClosed("A peer sent an incomplete message");
          }
        }, 1e3);
        if (typeof this.expiryTimer === "object" && this.expiryTimer && typeof this.expiryTimer.unref === "function") {
          this.expiryTimer.unref();
        }
      }
      const unsubscribe = this.signalling.onMessage(this.onSignal);
      if (this.direct && typeof unsubscribe === "function") {
        this.unsubscribeSignalling = unsubscribe;
      }
    }
    get bufferedAmount() {
      let total = 0;
      for (const state of this.channelStates) total += state.queue.bufferedAmount;
      return total;
    }
    /** Bytes queued on one channel (spec index, or `0` in single-channel mode). */
    bufferedAmountOn(channelIndex) {
      return this.channelStates[channelIndex]?.queue.bufferedAmount ?? 0;
    }
    on(event, handler) {
      this.emitter.on(event, handler);
    }
    async send(value) {
      await this.sendOn(0, value);
    }
    /**
     * Send one value on the given channel; resolves `undefined` once the payload
     * has been handed to the send queue (default JSON mode, preserving the
     * historical `Promise<void>` contract). In raw mode (`raw: true`) binary
     * payloads cross byte-for-byte: on `"drop"`-policy channels the promise
     * rejects with {@link RTCTransportBackpressureDropError} when the payload is
     * rejected under backpressure (use {@link trySendOn} for synchronous
     * acceptance); on `"queue"`-policy channels it never rejects for that reason.
     */
    async sendOn(channelIndex, value) {
      const state = this.channelStates[channelIndex];
      if (!state || state.channel.readyState !== "open") {
        throw new Error("RTC transport is not open");
      }
      if (this.raw) {
        const bytes = toUint8Array(value);
        if (state.spec?.mode === "drop") {
          if (!state.queue.trySend(bytes)) throw new RTCTransportBackpressureDropError(channelIndex);
          return;
        }
        await state.queue.send(bytes);
        return;
      }
      if (this.direct) {
        const packets = [...state.chunker.split(randomId(8), JSON.stringify(value))];
        try {
          await state.queue.sendJob(packets);
        } catch (err) {
          this.failClosed("Direct connection send queue is full");
          throw err;
        }
        return;
      }
      const groupId = randomId(8);
      const data = JSON.stringify(value);
      for (const packet of state.chunker.split(groupId, data)) {
        await state.queue.send(packet);
      }
    }
    /**
     * Synchronous bounded acceptance for direct-mode JSON sends: the value is
     * fragmented and handed to the channel's bounded job queue, and this returns
     * whether it was accepted — never a promise masquerading as success. Delivery
     * completes silently (a synchronous producer, e.g. an Emscripten `ccall`
     * bridge, cannot await); the link's health, including a later close that
     * abandons an accepted job, surfaces on the `error`/`disconnect` events.
     * A value that cannot be framed under the hardened limits fails the link
     * (fail-closed, like the send-queue bound) and returns `false`.
     *
     * Throws outside direct mode (`options.direct`), which is the JSON-mode
     * counterpart of {@link trySendOn}'s raw-mode guard.
     */
    trySend(value) {
      if (!this.direct) throw new Error("trySend requires direct mode (options.direct)");
      const state = this.channelStates[0];
      if (!state || state.channel.readyState !== "open") return false;
      try {
        const packets = [...state.chunker.split(randomId(8), JSON.stringify(value))];
        return state.queue.tryJob(packets);
      } catch {
        this.failClosed("Direct connection could not deliver a message");
        return false;
      }
    }
    /**
     * Synchronous acceptance for raw mode: queues on `"queue"`-policy channels
     * (fire-and-forget) and returns whether the payload was accepted; on
     * `"drop"`-policy channels returns `false` when it was rejected under
     * backpressure instead of queueing stale lossy state.
     *
     * Why this exists beside the async {@link sendOn}: Emscripten `ccall`
     * exports and other synchronous producers must learn send acceptance in the
     * same tick; a promise resolves too late to substitute fresh state.
     */
    trySendOn(channelIndex, value) {
      if (!this.raw) throw new Error("trySendOn requires raw mode (options.raw)");
      const state = this.channelStates[channelIndex];
      if (!state || state.channel.readyState !== "open") return false;
      const bytes = toUint8Array(value);
      if (state.spec?.mode === "drop") return state.queue.trySend(bytes);
      state.queue.send(bytes).catch((err) => {
        this.emitter.emit("error", err instanceof Error ? err : new Error(String(err)));
      });
      return true;
    }
    /**
     * Last known round-trip time estimate for this link in milliseconds, from
     * polling `pc.getStats()` while connected; 0 when not connected.
     *
     * Why cached instead of exposing `getStats()` directly: synchronous C
     * exports (Emscripten `ccall`) cannot await a promise, so the transport
     * keeps a freshest-known value.
     */
    getRoundTripTimeMs() {
      return this.rttMs;
    }
    disconnect() {
      this.closed = true;
      this.clearConnectTimer();
      this.stopRttPolling();
      this.stopExpiryTimer();
      for (const state of this.channelStates) {
        state.queue.detach();
        try {
          state.channel.close();
        } catch {
        }
      }
      try {
        this.pc.close();
      } catch {
      }
      this.handleClose();
    }
    /**
     * Direct-mode fail-closed path: emit the cause once, then tear the link down
     * (`disconnect` emits the single `disconnect`; pending send jobs are rejected
     * by their queue detaching). Accepts the finished `Error` directly so a
     * native send failure reaches consumers unaltered.
     */
    failClosed(cause) {
      if (this.closed || this.emittedClose) return;
      try {
        this.emitter.emit("error", cause instanceof Error ? cause : new Error(cause));
      } finally {
        this.disconnect();
      }
    }
    stopExpiryTimer() {
      if (this.expiryTimer !== void 0) {
        clearInterval(this.expiryTimer);
        this.expiryTimer = void 0;
      }
    }
    setupChannel(index, channel, options) {
      if (this.direct && (channel.label !== (options.label ?? "p2pkit") || !channel.ordered || !isFullyReliable(channel.maxRetransmits) || !isFullyReliable(channel.maxPacketLifeTime))) {
        try {
          channel.close();
        } catch {
        }
        this.failClosed("Invalid direct game channel");
        return;
      }
      const chunker = new Chunker({ maxPacketSize: options.chunkSize, hardened: this.direct });
      const queue = new RTCDataChannelSendQueue({
        highWaterBytes: options.channels?.[index]?.highWaterBytes ?? options.highWaterBytes ?? (this.direct ? DIRECT_MAX_BUFFERED : void 0),
        lowWaterBytes: options.channels?.[index]?.lowWaterBytes ?? options.lowWaterBytes,
        onDrain: () => this.emitter.emit("drain", index),
        // A native send() throw while flushing retained work (including delayed,
        // timer-driven drains) already rejected every pending job in the queue;
        // surface it exactly once on the transport's error path. Direct mode
        // fails the whole link (lockstep JSON cannot continue past a lost
        // fragment); other modes report the error without tearing the transport.
        onSendError: (error) => {
          if (this.direct) this.failClosed(error);
          else this.emitter.emit("error", error);
        },
        maxQueuedBytes: this.direct ? DIRECT_MAX_OUTGOING_BYTES : void 0,
        maxQueuedJobs: this.direct ? DIRECT_MAX_OUTGOING_MESSAGES : void 0
      });
      queue.attach(channel);
      this.channelStates[index] = {
        channel,
        queue,
        chunker,
        spec: this.channelSpecs?.[index],
        traffic: this.direct ? { start: performance.now(), packets: 0, bytes: 0 } : void 0
      };
      try {
        channel.binaryType = "arraybuffer";
      } catch {
      }
      channel.onopen = () => this.onChannelOpen(index);
      channel.onmessage = (ev) => this.onData(index, ev.data);
      channel.onclose = () => this.handleClose();
      channel.onerror = () => this.emitter.emit("error", new Error("RTC data channel error"));
      if (channel.readyState === "open") this.onChannelOpen(index);
    }
    onChannelOpen(index) {
      if (this.closed || this.connectEmitted) return;
      this.openChannels.add(index);
      if (this.openChannels.size >= this.expectedChannelCount) this.emitConnect();
    }
    emitConnect() {
      if (this.connectEmitted || this.closed) return;
      this.connectEmitted = true;
      this.clearConnectTimer();
      this.startRttPolling();
      this.emitter.emit("connect");
    }
    startRttPolling() {
      if (this.rttTimer || typeof this.pc.getStats !== "function") return;
      this.rttTimer = setInterval(() => {
        if (this.closed) {
          this.stopRttPolling();
          return;
        }
        this.pc.getStats().then((report) => {
          if (this.closed || this.rttTimer === void 0) return;
          let best = 0;
          report.forEach((entry) => {
            if (entry.type === "candidate-pair" && entry.state === "succeeded" && typeof entry.currentRoundTripTime === "number") {
              const ms = entry.currentRoundTripTime * 1e3;
              if (best === 0 || ms < best) best = ms;
            }
          });
          if (best > 0) this.rttMs = Math.round(best);
        }).catch(() => {
        });
      }, 2e3);
      if (typeof this.rttTimer === "object" && this.rttTimer && typeof this.rttTimer.unref === "function") {
        this.rttTimer.unref();
      }
    }
    stopRttPolling() {
      if (this.rttTimer !== void 0) {
        clearInterval(this.rttTimer);
        this.rttTimer = void 0;
      }
      this.rttMs = 0;
    }
    clearConnectTimer() {
      if (this.connectTimer !== void 0) {
        clearTimeout(this.connectTimer);
        this.connectTimer = void 0;
      }
    }
    handleConnectTimeout() {
      if (this.closed || this.connectEmitted || this.emittedClose) return;
      this.closed = true;
      this.clearConnectTimer();
      this.stopRttPolling();
      this.stopExpiryTimer();
      this.emitter.emit("error", new RTCTransportConnectTimeoutError(this.connectTimeoutMs));
      for (const state of this.channelStates) {
        state.queue.detach();
        try {
          state.channel.close();
        } catch {
        }
      }
      try {
        this.pc.close();
      } catch {
      }
      this.handleClose();
    }
    async negotiate() {
      await this.signalling.ready;
      const offer = await this.pc.createOffer();
      await this.pc.setLocalDescription(offer);
      this.sendDescription();
    }
    sendDescription() {
      const description = this.pc.localDescription;
      if (!description) return;
      if (this.direct) validateDirectDescription(description);
      this.signalling.send({
        description: { type: description.type, sdp: description.sdp },
        from: this.self,
        to: this.remote
      });
    }
    async handleSignal(message) {
      if (this.closed) return;
      if ("description" in message) {
        if (message.from !== this.remote || message.to !== this.self) return;
        if (this.direct) {
          validateDirectDescription(message.description);
          if (this.remoteDescriptionSet || message.description.type !== (this.initiator ? "answer" : "offer")) {
            throw new Error("Unexpected description");
          }
        }
        await this.pc.setRemoteDescription(message.description);
        this.remoteDescriptionSet = true;
        await this.flushCandidates();
        if (message.description.type === "offer") {
          const answer = await this.pc.createAnswer();
          await this.pc.setLocalDescription(answer);
          this.sendDescription();
        }
      } else if ("iceCandidate" in message) {
        if (message.from !== this.remote || message.to !== this.self) return;
        if (this.direct) {
          validateDirectCandidate(message.iceCandidate);
          if (++this.candidateCount > DIRECT_MAX_SIGNALS) throw new Error("Too many candidates");
        }
        if (this.remoteDescriptionSet) await this.pc.addIceCandidate(message.iceCandidate);
        else this.pendingCandidates.push(message.iceCandidate);
      }
    }
    async flushCandidates() {
      for (const candidate of this.pendingCandidates.splice(0)) {
        try {
          await this.pc.addIceCandidate(candidate);
        } catch {
        }
      }
    }
    onData(channelIndex, data) {
      const state = this.channelStates[channelIndex];
      if (!state) return;
      if (this.raw) {
        if (typeof data === "string") return;
        const bytes = data instanceof Uint8Array ? data : new Uint8Array(data);
        this.emitter.emit("message", bytes, channelIndex);
        return;
      }
      if (this.direct) {
        try {
          if ((typeof data === "string" ? data.length : data.byteLength) > DIRECT_MAX_FRAME_BYTES) {
            throw new Error("Oversized fragment");
          }
          const raw2 = typeof data === "string" ? data : new TextDecoder("utf-8", { fatal: true }).decode(data);
          const traffic = state.traffic ?? (state.traffic = { start: performance.now(), packets: 0, bytes: 0 });
          const now = performance.now();
          if (now - traffic.start >= 1e3) {
            traffic.start = now;
            traffic.packets = 0;
            traffic.bytes = 0;
          }
          traffic.packets++;
          traffic.bytes += typeof data === "string" ? textEncoder.encode(raw2).length : data.byteLength;
          if (traffic.packets > DIRECT_MAX_PACKETS_PER_SECOND || traffic.bytes > DIRECT_MAX_BYTES_PER_SECOND) {
            throw new Error("Peer traffic limit exceeded");
          }
          const full2 = state.chunker.ingest(JSON.parse(raw2));
          if (full2 !== void 0) this.emitter.emit("message", JSON.parse(full2), channelIndex);
        } catch {
          this.failClosed("A peer sent an invalid game frame");
        }
        return;
      }
      const raw = typeof data === "string" ? data : new TextDecoder().decode(data);
      let packet;
      try {
        packet = JSON.parse(raw);
      } catch {
        return;
      }
      const full = state.chunker.ingest(packet);
      if (full === void 0) return;
      try {
        this.emitter.emit("message", JSON.parse(full), channelIndex);
      } catch {
      }
    }
    handleClose() {
      if (this.emittedClose) return;
      this.emittedClose = true;
      this.clearConnectTimer();
      this.stopRttPolling();
      this.stopExpiryTimer();
      if (this.unsubscribeSignalling) {
        const unsubscribe = this.unsubscribeSignalling;
        this.unsubscribeSignalling = void 0;
        try {
          unsubscribe();
        } catch {
        }
      }
      for (const state of this.channelStates) {
        state.chunker.reset();
        state.queue.detach();
      }
      this.emitter.emit("disconnect");
    }
  };

  // platform/web/src/dune-direct-bridge.ts
  var State = { New: 0, Connecting: 1, Connected: 2, Failed: 3, Closed: 4 };
  var MAX_QUEUED_VALUES = 4096;
  var MAX_QUEUED_VALUE_BYTES = 4 * 1024 * 1024;
  var MAX_QUEUED_SIGNALS = 256;
  var MAX_SIGNAL_CHARS = 65536;
  var connections = /* @__PURE__ */ new Map();
  var nextHandle = 1;
  function encodeCandidate(candidate) {
    return `${candidate.sdpMid || "0"}|${candidate.candidate}`;
  }
  function decodeCandidate(payload) {
    const split = payload.indexOf("|");
    if (split < 0) return null;
    const sdpMid = payload.slice(0, split);
    const candidate = payload.slice(split + 1);
    if (!candidate) return null;
    return { candidate, sdpMid };
  }
  function fail(connection, reason) {
    if (connection.state !== State.Closed) connection.state = State.Failed;
    if (!connection.error) connection.error = reason;
    connection.values.length = 0;
    connection.valueBytes = 0;
    connection.signals.length = 0;
    try {
      connection.transport?.disconnect();
    } catch {
    }
  }
  function usable(connection) {
    return connection !== void 0 && connection.state !== State.Failed && connection.state !== State.Closed && connection.deliver !== null;
  }
  function parseIceServers(iceServersJson) {
    let parsed;
    try {
      parsed = JSON.parse(iceServersJson);
    } catch {
      return null;
    }
    if (!Array.isArray(parsed) || parsed.length > 8) return null;
    const servers = [];
    for (const url of parsed) {
      if (typeof url !== "string") return null;
      servers.push({ urls: url });
    }
    return servers;
  }
  function create(iceServersJson, initiator, label) {
    const iceServers = parseIceServers(iceServersJson);
    if (iceServers === null) return 0;
    const handle = nextHandle++;
    let resolveReady = () => {
    };
    const ready = new Promise((resolve) => {
      resolveReady = resolve;
    });
    const connection = {
      transport: void 0,
      deliver: null,
      ready: resolveReady,
      signals: [],
      values: [],
      valueBytes: 0,
      state: State.New,
      error: ""
    };
    const signalling = {
      ready,
      send(message) {
        if (connection.signals.length >= MAX_QUEUED_SIGNALS) {
          fail(connection, "local signal queue overflowed");
          return;
        }
        if ("description" in message) {
          const sdp = message.description.sdp ?? "";
          if (sdp.length > MAX_SIGNAL_CHARS) {
            fail(connection, "local description too large");
            return;
          }
          connection.signals.push(`${message.description.type === "answer" ? "answer" : "offer"}|${sdp}`);
        } else if ("iceCandidate" in message) {
          connection.signals.push(`candidate|${encodeCandidate(message.iceCandidate)}`);
        }
      },
      onMessage(handler) {
        connection.deliver = handler;
        return () => {
          if (connection.deliver === handler) connection.deliver = null;
        };
      }
    };
    let peerConnection;
    try {
      class GamePeerConnection extends globalThis.RTCPeerConnection {
        constructor(config) {
          super(config);
          peerConnection = this;
        }
      }
      connection.transport = new RTCTransport({
        self: "local",
        remote: "remote",
        signalling,
        backend: { RTCPeerConnection: GamePeerConnection },
        // Exactly the servers the signaling service named, and no others. An empty list means host
        // candidates only, which is the right answer on a LAN; falling back to P2PKit's public STUN
        // defaults would contact a third party this game never told the player about. Direct mode
        // has the SDK enforce that this list is STUN-only before it reaches the peer connection.
        iceServers,
        initiator,
        label,
        direct: true
      });
    } catch {
      return 0;
    }
    const pc = peerConnection;
    const stateChanged = pc.onconnectionstatechange;
    pc.onconnectionstatechange = (event) => {
      if (["failed", "closed", "disconnected"].includes(pc.connectionState)) {
        const ice = ["new", "checking", "connected", "completed", "disconnected", "failed", "closed"].includes(pc.iceConnectionState) ? pc.iceConnectionState : "unknown";
        fail(connection, `WebRTC ${pc.connectionState}; ICE ${ice}`);
      } else {
        stateChanged?.call(pc, event);
      }
    };
    connection.transport.on("connect", () => {
      if (connection.state !== State.Failed && connection.state !== State.Closed) {
        connection.state = State.Connected;
      }
    });
    connection.transport.on("message", (value) => {
      if (connection.state === State.Failed || connection.state === State.Closed) return;
      if (typeof value !== "string") {
        fail(connection, "peer sent a non-string payload");
        return;
      }
      if (connection.values.length >= MAX_QUEUED_VALUES || connection.valueBytes + value.length > MAX_QUEUED_VALUE_BYTES) {
        fail(connection, "this computer could not keep up with a player's messages");
        return;
      }
      connection.valueBytes += value.length;
      connection.values.push(value);
    });
    connection.transport.on("disconnect", () => {
      if (connection.state !== State.Failed) connection.state = State.Closed;
    });
    connection.transport.on("error", (error) => {
      fail(connection, error instanceof Error ? error.message : "data channel error");
    });
    resolveReady();
    connection.state = State.Connecting;
    connections.set(handle, connection);
    return handle;
  }
  var bridge = {
    create,
    /** Applies a remote offer or answer. The C++ side has already checked the fingerprint. */
    setRemoteDescription(handle, kind, sdp) {
      const connection = connections.get(handle);
      if (!usable(connection)) return false;
      connection.deliver({
        description: { type: kind === "answer" ? "answer" : "offer", sdp },
        from: "remote",
        to: "local"
      });
      return true;
    },
    addRemoteCandidate(handle, payload) {
      const connection = connections.get(handle);
      if (!usable(connection)) return false;
      const candidate = decodeCandidate(payload);
      if (!candidate) return false;
      connection.deliver({ iceCandidate: candidate, from: "remote", to: "local" });
      return true;
    },
    /** Sends one envelope. The text is a JSON value; RTCTransport fragments it. */
    sendValue(handle, text) {
      const connection = connections.get(handle);
      if (!connection || connection.state !== State.Connected) return false;
      if (connection.transport.bufferedAmount > 4 * 1024 * 1024) return false;
      let value;
      try {
        value = JSON.parse(text);
      } catch {
        return false;
      }
      if (typeof value !== "string") return false;
      const accepted = connection.transport.trySend(value);
      return accepted && connection.state === State.Connected;
    },
    /** Takes one received envelope as JSON text, or null. */
    pollValue(handle) {
      const connection = connections.get(handle);
      if (!connection || connection.values.length === 0) return null;
      const value = connection.values.shift();
      connection.valueBytes -= value.length;
      return JSON.stringify(value);
    },
    /** Takes one locally produced signal as "<kind>|<payload>", or null. */
    pollSignal(handle) {
      const connection = connections.get(handle);
      if (!connection || connection.signals.length === 0) return null;
      return connection.signals.shift();
    },
    bufferedAmount(handle) {
      const connection = connections.get(handle);
      return connection ? connection.transport.bufferedAmount : 0;
    },
    state(handle) {
      const connection = connections.get(handle);
      return connection ? connection.state : State.Closed;
    },
    lastError(handle) {
      const connection = connections.get(handle);
      return connection ? connection.error : "";
    },
    close(handle) {
      const connection = connections.get(handle);
      if (!connection) return;
      try {
        connection.transport.disconnect();
      } catch {
      }
      connection.state = State.Closed;
      connection.values.length = 0;
      connection.signals.length = 0;
      connections.delete(handle);
    }
  };
  globalThis.DuneDirectBridge = bridge;
  var dune_direct_bridge_default = bridge;
})();
