#!/usr/bin/env python3
"""Generate the runtime catalog for independently downloaded Dune2R art."""

from __future__ import annotations

import argparse
import hashlib
import subprocess
from pathlib import Path


DISPLAY_NAMES = {
    "gravel": "Gravel Terrain Remastered",
    "sand": "Sand Terrain Remastered",
    "harkonnendevastator": "Harkonnen Devastator Remastered",
    "ordostank": "Ordos Tank Remastered",
    "refinery": "Atreides Refinery Remastered",
}


def git_revision(repo: Path, revision: str = "HEAD") -> str:
    return subprocess.check_output(
        ["git", "rev-parse", revision], cwd=repo, text=True
    ).strip()


def git_blob(repo: Path, revision: str, path: Path) -> bytes:
    relative = path.relative_to(repo).as_posix()
    return subprocess.check_output(["git", "show", f"{revision}:{relative}"], cwd=repo)


def build_catalog(repo: Path, revision: str) -> str:
    revision = git_revision(repo, revision)
    prefix = "mods/Dune2R/graphics_hd/units/"
    paths = subprocess.check_output(
        ["git", "ls-tree", "-r", "--name-only", "-z", revision, "--", prefix], cwd=repo
    ).decode("utf-8").split("\0")
    units = {}
    for path in paths:
        if not path or path.endswith("/.gitkeep"):
            continue
        unit, separator, relative = path[len(prefix):].partition("/")
        if separator and not unit.startswith("."):
            units.setdefault(unit, []).append(relative)
    lines = [
        "# Generated by scripts/generate-dune2r-asset-catalog.py",
        "# URLs are pinned to an immutable public game commit.",
        "[Catalog]",
        "Schema=1",
        f"Revision={revision}",
        "BaseURL=https://raw.githubusercontent.com/VR48/dunecity/"
        f"{revision}/mods/Dune2R/graphics_hd/units",
        f"PackCount={len(units)}",
        "",
    ]

    for pack_index, (unit, files) in enumerate(sorted(units.items())):
        lines.extend(
            [
                f"[Pack.{pack_index}]",
                f"ID={unit}",
                f"DisplayName={DISPLAY_NAMES.get(unit, unit)}",
                "Variant=remastered",
                f"Unit={unit}",
                f"FileCount={len(files)}",
            ]
        )
        for file_index, relative in enumerate(sorted(files)):
            blob = git_blob(repo, revision, repo / prefix / unit / relative)
            digest = hashlib.sha256(blob).hexdigest()
            lines.append(f"File.{file_index}={relative}|{len(blob)}|{digest}")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--revision", help="Immutable Git revision containing the assets")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    repo = args.repo.resolve()
    revision = git_revision(repo, args.revision or "HEAD")
    output = args.output or repo / "mods/Dune2R/asset-catalog.ini"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_catalog(repo, revision), encoding="ascii", newline="\n")
    print(f"Wrote {output} pinned to {revision}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
