import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('../../', import.meta.url));
await build({
  entryPoints: [path.join(root, 'platform/web/src/dune-direct-bridge.ts')],
  outfile: path.join(root, 'platform/web/p2p-direct.js'),
  bundle: true, format: 'iife', platform: 'browser', target: ['es2020'],
  minify: false, legalComments: 'inline', sourcemap: false,
  banner: {js: '// DuneCity direct transport. Bundled from the installed p2pkit dependency pinned in platform/web/package.json (github:QuixThe2nd/p2pkit#257f3c8eb0c0cf373298225e54c8d09d2f896a42, MIT) via its documented package exports. Generated by tools/p2pkit-build/build.mjs.'},
});
